from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from nomarr.persistence.stubs._base import GetModifierProtocol

@runtime_checkable
class LibraryContainsFileFromNamespace(Protocol):
    get: GetModifierProtocol

    def count(self, value: str) -> int: ...
    def delete(self, value: str) -> int: ...
    def collect(self, *, limit: int | None = ..., offset: int = ...) -> list[Any]: ...

@runtime_checkable
class LibraryContainsFileToNamespace(Protocol):
    get: GetModifierProtocol

    def collect(self, *, limit: int | None = ..., offset: int = ...) -> list[Any]: ...
    def delete(self, value: str) -> int: ...
    def upsert(self, docs: list[dict[str, Any]], match_field: str | list[str]) -> list[str]: ...

@runtime_checkable
class LibraryContainsFileNamespace(Protocol):
    _from: LibraryContainsFileFromNamespace
    _to: LibraryContainsFileToNamespace

    def count(self) -> int: ...
    def get(self, id: str) -> dict[str, Any] | None: ...
    def insert(self, docs: list[dict[str, Any]]) -> list[str]: ...
    def delete(self, ids: list[str]) -> None: ...
