from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from nomarr.persistence.stubs._base import CollectionGetProtocol, GetModifierProtocol

@runtime_checkable
class VectorsTrackGetOnlyNamespace(Protocol):
    get: GetModifierProtocol

@runtime_checkable
class VectorsTrackIdNamespace(Protocol):
    get: GetModifierProtocol

    def collect(
        self,
        *,
        filter: dict[str, Any] | None = ...,
        limit: int | None = ...,
        offset: int = ...,
    ) -> list[Any]: ...

@runtime_checkable
class VectorsTrackFileIdNamespace(Protocol):
    get: GetModifierProtocol

    def delete(self, value: str) -> int: ...

@runtime_checkable
class VectorsTrackHotNamespace(Protocol):
    get: CollectionGetProtocol
    _key: VectorsTrackGetOnlyNamespace
    _id: VectorsTrackIdNamespace
    file_id: VectorsTrackFileIdNamespace
    vector: VectorsTrackGetOnlyNamespace

    def count(self) -> int: ...
    def count_by_filter(self, filter_dict: dict[str, Any]) -> int: ...
    def insert(self, docs: list[dict[str, Any]]) -> list[str]: ...
    def delete(self, ids: list[str]) -> None: ...
    def delete_by_filter(self, filter_dict: dict[str, Any]) -> int: ...
    def update_by_filter(self, filter_dict: dict[str, Any], fields: dict[str, Any]) -> None: ...
    def cascade(self, ids: list[str]) -> int: ...
    def truncate(self) -> None: ...
    def ann_search(
        self,
        query_vector: list[float],
        limit: int,
        nprobe: int,
        *,
        filter: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]: ...
    def get_vector(self, file_id: str) -> dict[str, Any] | None: ...
    def get_vectors_by_file_ids(self, file_ids: list[str]) -> list[dict[str, Any]]: ...
    def upsert_vector(
        self,
        file_id: str,
        model_suite_hash: str,
        embed_dim: int,
        vector: list[float],
        num_segments: int,
    ) -> None: ...

@runtime_checkable
class VectorsTrackColdNamespace(Protocol):
    get: CollectionGetProtocol
    _key: VectorsTrackGetOnlyNamespace
    _id: VectorsTrackIdNamespace
    file_id: VectorsTrackFileIdNamespace
    vector: VectorsTrackGetOnlyNamespace

    def count(self) -> int: ...
    def count_by_filter(self, filter_dict: dict[str, Any]) -> int: ...
    def insert(self, docs: list[dict[str, Any]]) -> list[str]: ...
    def delete(self, ids: list[str]) -> None: ...
    def delete_by_filter(self, filter_dict: dict[str, Any]) -> int: ...
    def update_by_filter(self, filter_dict: dict[str, Any], fields: dict[str, Any]) -> None: ...
    def cascade(self, ids: list[str]) -> int: ...
    def truncate(self) -> None: ...
    def ann_search(
        self,
        query_vector: list[float],
        limit: int,
        nprobe: int,
        *,
        filter: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]: ...
    def get_vector(self, file_id: str) -> dict[str, Any] | None: ...
    def get_vectors_by_file_ids(self, file_ids: list[str]) -> list[dict[str, Any]]: ...

@runtime_checkable
class VectorsTrackMaintenanceProtocol(Protocol):
    def drain_to_cold(self) -> int: ...
    def ensure_cold_collection(self) -> None: ...
    def drop_index(self) -> None: ...
    def build_index(self, *, embed_dim: int, nlists: int) -> None: ...
    def rebuild_index(self, *, embed_dim: int, nlists: int) -> None: ...
    def get_stats(self) -> dict[str, int | bool]: ...
