"""
Tests for Navidrome playlist templates.
"""

import json

from nomarr.services.navidrome.templates import (
    generate_template_files,
    get_all_templates,
    get_mixed_templates,
    get_mood_templates,
    get_quality_templates,
    get_style_templates,
    get_template_summary,
)


def test_get_mood_templates():
    """Test mood-based templates exist."""
    templates = get_mood_templates()

    assert len(templates) > 0
    assert "happy_energetic.nsp" in templates
    assert "sad_melancholic.nsp" in templates
    assert "relaxed_calm.nsp" in templates

    # Check structure
    for filename, content in templates.items():
        assert filename.endswith(".nsp")
        assert "name" in content
        assert "comment" in content
        assert "Auto-generated by Nomarr" in content["comment"]


def test_get_style_templates():
    """Test style-based templates exist."""
    templates = get_style_templates()

    assert len(templates) > 0
    assert "bright_electronic.nsp" in templates
    assert "dark_acoustic.nsp" in templates
    assert "highly_danceable.nsp" in templates


def test_get_quality_templates():
    """Test quality-based templates exist."""
    templates = get_quality_templates()

    assert len(templates) > 0
    assert "approachable_engaging.nsp" in templates
    assert "challenging_listen.nsp" in templates
    assert "high_engagement.nsp" in templates


def test_get_mixed_templates():
    """Test mixed-criteria templates exist."""
    templates = get_mixed_templates()

    assert len(templates) > 0
    assert "party_mix.nsp" in templates
    assert "chill_acoustic.nsp" in templates
    assert "upbeat_electronic.nsp" in templates


def test_get_all_templates():
    """Test all templates combined."""
    templates = get_all_templates()

    # Should have templates from all categories
    assert len(templates) >= 12

    # Check no duplicates
    assert len(templates) == len(set(templates.keys()))

    # All should be valid .nsp structures
    for content in templates.values():
        assert "name" in content
        assert "comment" in content
        # Should have either 'all' or 'any' rules
        assert "all" in content or "any" in content


def test_generate_template_files():
    """Test generating template files as JSON strings."""
    templates = generate_template_files()

    assert len(templates) > 0

    # All should be valid JSON
    for filename, content in templates.items():
        assert filename.endswith(".nsp")

        # Parse JSON to verify it's valid
        parsed = json.loads(content)
        assert "name" in parsed
        assert "comment" in parsed


def test_get_template_summary():
    """Test template summary generation."""
    summary = get_template_summary()

    assert len(summary) > 0

    # Check structure
    for item in summary:
        assert "filename" in item
        assert "name" in item
        assert "comment" in item
        assert item["filename"].endswith(".nsp")


def test_template_nsp_structure():
    """Test that templates have valid .nsp structure."""
    templates = get_all_templates()

    for filename, content in templates.items():
        # Required fields
        assert isinstance(content["name"], str)
        assert isinstance(content["comment"], str)

        # Should have rules (all or any)
        has_rules = "all" in content or "any" in content
        assert has_rules, f"{filename} has no rules"

        # Optional fields
        if "sort" in content:
            assert isinstance(content["sort"], str)
        if "limit" in content:
            assert isinstance(content["limit"], int)
            assert content["limit"] > 0


def test_template_operators():
    """Test that templates use valid Navidrome operators."""
    templates = get_all_templates()
    valid_operators = {"gt", "lt", "is", "contains", "any", "all"}

    for filename, content in templates.items():
        # Get all rules
        all_rules = content.get("all", []) + content.get("any", [])

        for rule in all_rules:
            # Each rule should be a dict with operator as key
            assert isinstance(rule, dict)

            for operator in rule:
                # Handle nested 'any' and 'all'
                if operator in ("any", "all"):
                    continue

                assert operator in valid_operators, f"{filename} has invalid operator: {operator}"


def test_template_field_names():
    """Test that templates use valid field names (no namespace prefix)."""
    templates = get_all_templates()

    for filename, content in templates.items():
        all_rules = content.get("all", []) + content.get("any", [])

        for rule in all_rules:
            for operator, field_dict in rule.items():
                if operator in ("any", "all"):
                    # Nested rules
                    continue

                # field_dict should be {field_name: value}
                for field_name in field_dict:
                    # Should not have namespace prefix
                    assert not field_name.startswith("nom:"), f"{filename} has namespaced field: {field_name}"
                    assert not field_name.startswith("essentia:"), f"{filename} has namespaced field: {field_name}"
