"""V001: Consolidated baseline schema — replaces V004\u2013V019.

This migration was generated by ``scripts/consolidate_migrations``
and represents the cumulative schema state after replaying all
migrations from V004 through V019.  It idempotently creates all
collections, indexes, graphs, and seed documents.

Blacklisted dynamic collection patterns (e.g. per-model vector
collections) are intentionally excluded — they are created at
runtime by ``ensure_schema()`` based on the current model state.

Forward-only; no downgrade path.
"""

from __future__ import annotations

import contextlib
import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from nomarr.persistence.arango_client import DatabaseLike

logger = logging.getLogger(__name__)

# Required metadata
MIGRATION_VERSION: str = "0.0.0"
DESCRIPTION: str = "Consolidated baseline schema — replaces V004\u2013V019"


def upgrade(db: DatabaseLike) -> None:
    """Create all schema objects idempotently.

    This is the consolidated baseline migration produced by the
    consolidation tool.  It creates all collections, indexes, graphs,
    and seed documents previously spread across V004\u2013V019.

    Safe to run multiple times — all operations use ``has_collection``
    or ``try/except`` guards to avoid errors on re-run.

    Args:
        db: ArangoDB database handle.

    """
    from arango.exceptions import CollectionCreateError, GraphCreateError, IndexCreateError

    # -- Document collections --
    if not db.has_collection("applied_migrations"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("applied_migrations")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection applied_migrations")
    if not db.has_collection("calibration_history"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("calibration_history")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection calibration_history")
    if not db.has_collection("calibration_state"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("calibration_state")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection calibration_state")
    if not db.has_collection("file_states"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("file_states")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection file_states")
    if not db.has_collection("health"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("health")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection health")
    if not db.has_collection("libraries"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("libraries")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection libraries")
    if not db.has_collection("library_files"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("library_files")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection library_files")
    if not db.has_collection("library_folders"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("library_folders")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection library_folders")
    if not db.has_collection("meta"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("meta")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection meta")
    if not db.has_collection("ml_capacity_estimates"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("ml_capacity_estimates")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection ml_capacity_estimates")
    if not db.has_collection("ml_capacity_probe_locks"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("ml_capacity_probe_locks")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection ml_capacity_probe_locks")
    if not db.has_collection("ml_model_outputs"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("ml_model_outputs")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection ml_model_outputs")
    if not db.has_collection("ml_models"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("ml_models")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection ml_models")
    if not db.has_collection("navidrome_playcounts"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("navidrome_playcounts")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection navidrome_playcounts")
    if not db.has_collection("navidrome_tracks"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("navidrome_tracks")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection navidrome_tracks")
    if not db.has_collection("segment_scores_stats"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("segment_scores_stats")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection segment_scores_stats")
    if not db.has_collection("sessions"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("sessions")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection sessions")
    if not db.has_collection("tags"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("tags")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection tags")
    if not db.has_collection("vector_promotion_locks"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("vector_promotion_locks")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection vector_promotion_locks")
    if not db.has_collection("vram_promises"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("vram_promises")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection vram_promises")
    if not db.has_collection("worker_claims"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("worker_claims")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection worker_claims")
    if not db.has_collection("worker_restart_policy"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("worker_restart_policy")  # type: ignore[union-attr]
            logger.info("[V001] Created document collection worker_restart_policy")

    # -- Edge collections --
    if not db.has_collection("file_has_state"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("file_has_state", edge=True)  # type: ignore[union-attr]
            logger.info("[V001] Created edge collection file_has_state")
    if not db.has_collection("has_nd_id"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("has_nd_id", edge=True)  # type: ignore[union-attr]
            logger.info("[V001] Created edge collection has_nd_id")
    if not db.has_collection("has_plays"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("has_plays", edge=True)  # type: ignore[union-attr]
            logger.info("[V001] Created edge collection has_plays")
    if not db.has_collection("song_has_tags"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("song_has_tags", edge=True)  # type: ignore[union-attr]
            logger.info("[V001] Created edge collection song_has_tags")
    if not db.has_collection("tag_model_output"):  # type: ignore[union-attr]
        with contextlib.suppress(CollectionCreateError):
            db.create_collection("tag_model_output", edge=True)  # type: ignore[union-attr]
            logger.info("[V001] Created edge collection tag_model_output")

    # -- Indexes --
    with contextlib.suppress(IndexCreateError):
        db.collection("calibration_history").add_persistent_index(fields=["calibration_key"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("calibration_history").add_persistent_index(fields=["snapshot_at"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("calibration_state").add_persistent_index(fields=["calibration_def_hash"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("calibration_state").add_persistent_index(fields=["updated_at"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("file_has_state").add_persistent_index(fields=["_from", "_to"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("file_has_state").add_persistent_index(fields=["_to"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("has_nd_id").add_persistent_index(fields=["_from", "_to"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("has_nd_id").add_persistent_index(fields=["_to"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("has_plays").add_persistent_index(fields=["_from", "_to"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("has_plays").add_persistent_index(fields=["_to"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("health").add_persistent_index(fields=["component_id"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("libraries").add_persistent_index(fields=["is_enabled"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["calibration_hash"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["chromaprint"], sparse=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["library_id"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["library_id", "normalized_path"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["library_id", "path"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["library_id", "tagged"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["needs_tagging", "is_valid"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["normalized_path"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["path"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_files").add_persistent_index(fields=["write_claimed_by"], sparse=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_folders").add_persistent_index(fields=["library_id"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("library_folders").add_persistent_index(fields=["library_id", "path"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("meta").add_persistent_index(fields=["key"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("ml_model_outputs").add_persistent_index(fields=["model_id", "output_index"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("ml_models").add_persistent_index(fields=["path"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("navidrome_playcounts").add_persistent_index(fields=["userid", "playcount"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("segment_scores_stats").add_persistent_index(fields=["file_id"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("segment_scores_stats").add_persistent_index(fields=["file_id", "head_name", "tagger_version"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("segment_scores_stats").add_persistent_index(fields=["head_name"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("segment_scores_stats").add_persistent_index(fields=["tagger_version"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("sessions").add_persistent_index(fields=["session_id"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("sessions").add_ttl_index(  # type: ignore[union-attr]
            fields=["expiry_timestamp"], expiry_time=0
        )
    with contextlib.suppress(IndexCreateError):
        db.collection("song_has_tags").add_persistent_index(fields=["_from"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("song_has_tags").add_persistent_index(fields=["_from", "_to"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("song_has_tags").add_persistent_index(fields=["_to"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("tag_model_output").add_persistent_index(fields=["_to"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("tags").add_persistent_index(fields=["rel"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("tags").add_persistent_index(fields=["rel", "value"], unique=True)  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("worker_claims").add_persistent_index(fields=["claimed_at"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("worker_claims").add_persistent_index(fields=["file_key"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("worker_claims").add_persistent_index(fields=["worker_id"])  # type: ignore[union-attr]
    with contextlib.suppress(IndexCreateError):
        db.collection("worker_restart_policy").add_persistent_index(fields=["component_id"])  # type: ignore[union-attr]

    # -- Graphs --
    if not db.has_graph("navidrome_graph"):  # type: ignore[union-attr]
        with contextlib.suppress(GraphCreateError):
            db.create_graph(  # type: ignore[union-attr]
                "navidrome_graph",
                edge_definitions=[
                    {
                        "edge_collection": "has_nd_id",
                        "from_vertex_collections": ["navidrome_tracks"],
                        "to_vertex_collections": ["library_files"],
                    },
                    {
                        "edge_collection": "has_plays",
                        "from_vertex_collections": ["navidrome_tracks"],
                        "to_vertex_collections": ["navidrome_playcounts"],
                    },
                ],
            )
            logger.info("[V001] Created graph navidrome_graph")
    if not db.has_graph("tag_graph"):  # type: ignore[union-attr]
        with contextlib.suppress(GraphCreateError):
            db.create_graph(  # type: ignore[union-attr]
                "tag_graph",
                edge_definitions=[
                    {
                        "edge_collection": "song_has_tags",
                        "from_vertex_collections": ["library_files"],
                        "to_vertex_collections": ["tags"],
                    },
                ],
            )
            logger.info("[V001] Created graph tag_graph")

    # -- Seed documents --
    if not db.collection("file_states").get("calibrated"):  # type: ignore[union-attr]
        with contextlib.suppress(Exception):
            db.collection("file_states").insert(  # type: ignore[union-attr]
                {"_key": "calibrated"}, silent=True
            )
            logger.info("[V001] Inserted seed document file_states/calibrated")
    if not db.collection("file_states").get("ml_tagged"):  # type: ignore[union-attr]
        with contextlib.suppress(Exception):
            db.collection("file_states").insert(  # type: ignore[union-attr]
                {"_key": "ml_tagged"}, silent=True
            )
            logger.info("[V001] Inserted seed document file_states/ml_tagged")
    if not db.collection("file_states").get("reconciled"):  # type: ignore[union-attr]
        with contextlib.suppress(Exception):
            db.collection("file_states").insert(  # type: ignore[union-attr]
                {"_key": "reconciled"}, silent=True
            )
            logger.info("[V001] Inserted seed document file_states/reconciled")
