"""
Predefined Smart Playlist templates for Navidrome.

These templates provide common playlist configurations that users can
generate in bulk and customize for their library.
"""

import json
from typing import Any


def get_mood_templates() -> dict[str, dict[str, Any]]:
    """Get mood-based playlist templates."""
    return {
        "happy_energetic.nsp": {
            "name": "Happy & Energetic",
            "comment": "High-energy positive tracks - Auto-generated by Nomarr",
            "any": [
                {"contains": {"mood_strict": "happy"}},
                {"contains": {"mood_strict": "energetic"}},
                {"contains": {"mood_regular": "happy"}},
                {"contains": {"mood_regular": "energetic"}},
            ],
            "sort": "-engagement,random",
            "limit": 100,
        },
        "sad_melancholic.nsp": {
            "name": "Sad & Melancholic",
            "comment": "Emotional, introspective tracks - Auto-generated by Nomarr",
            "any": [
                {"contains": {"mood_strict": "sad"}},
                {"contains": {"mood_strict": "melancholic"}},
                {"contains": {"mood_regular": "sad"}},
                {"contains": {"mood_regular": "melancholic"}},
            ],
            "sort": "-approachability,title",
            "limit": 100,
        },
        "relaxed_calm.nsp": {
            "name": "Relaxed & Calm",
            "comment": "Low-energy chill tracks - Auto-generated by Nomarr",
            "all": [
                {
                    "any": [
                        {"contains": {"mood_strict": "relaxed"}},
                        {"contains": {"mood_strict": "calm"}},
                        {"contains": {"mood_regular": "relaxed"}},
                        {"contains": {"mood_regular": "calm"}},
                    ]
                },
                {"lt": {"engagement": 0.6}},
            ],
            "sort": "approachability,-rating",
            "limit": 100,
        },
        "aggressive_intense.nsp": {
            "name": "Aggressive & Intense",
            "comment": "Heavy, intense tracks - Auto-generated by Nomarr",
            "all": [
                {
                    "any": [
                        {"contains": {"mood_strict": "aggressive"}},
                        {"contains": {"mood_strict": "intense"}},
                        {"contains": {"mood_regular": "aggressive"}},
                    ]
                },
                {"gt": {"engagement": 0.6}},
            ],
            "sort": "-engagement,random",
            "limit": 100,
        },
    }


def get_style_templates() -> dict[str, dict[str, Any]]:
    """Get style-based playlist templates."""
    return {
        "bright_electronic.nsp": {
            "name": "Bright Electronic",
            "comment": "Bright electronic music - Auto-generated by Nomarr",
            "all": [
                {"contains": {"nsynth_acoustic_electronic": "electronic"}},
                {"contains": {"nsynth_bright_dark": "bright"}},
            ],
            "sort": "-engagement,title",
            "limit": 100,
        },
        "dark_acoustic.nsp": {
            "name": "Dark Acoustic",
            "comment": "Dark acoustic tracks - Auto-generated by Nomarr",
            "all": [
                {"contains": {"nsynth_acoustic_electronic": "acoustic"}},
                {"contains": {"nsynth_bright_dark": "dark"}},
            ],
            "sort": "-approachability,title",
            "limit": 100,
        },
        "highly_danceable.nsp": {
            "name": "Highly Danceable",
            "comment": "Top dance tracks - Auto-generated by Nomarr",
            "all": [
                {"contains": {"danceability": "danceable"}},
                {"gt": {"engagement": 0.5}},
            ],
            "sort": "-engagement,random",
            "limit": 150,
        },
        "ambient_atmospheric.nsp": {
            "name": "Ambient & Atmospheric",
            "comment": "Atmospheric, spacious tracks - Auto-generated by Nomarr",
            "all": [
                {"contains": {"timbre": "bright"}},
                {"lt": {"engagement": 0.5}},
            ],
            "sort": "approachability,title",
            "limit": 100,
        },
    }


def get_quality_templates() -> dict[str, dict[str, Any]]:
    """Get quality/engagement-based playlist templates."""
    return {
        "approachable_engaging.nsp": {
            "name": "Approachable but Engaging",
            "comment": "Easy-listening but interesting - Auto-generated by Nomarr",
            "all": [
                {"gt": {"approachability": 0.6}},
                {"gt": {"engagement": 0.6}},
            ],
            "sort": "-engagement,-approachability",
            "limit": 100,
        },
        "challenging_listen.nsp": {
            "name": "Challenging Listen",
            "comment": "Complex, less approachable tracks - Auto-generated by Nomarr",
            "all": [
                {"lt": {"approachability": 0.4}},
                {"gt": {"engagement": 0.5}},
            ],
            "sort": "-engagement,title",
            "limit": 75,
        },
        "high_engagement.nsp": {
            "name": "High Engagement",
            "comment": "Most engaging tracks - Auto-generated by Nomarr",
            "all": [{"gt": {"engagement": 0.7}}],
            "sort": "-engagement,random",
            "limit": 100,
        },
        "easy_listening.nsp": {
            "name": "Easy Listening",
            "comment": "Highly approachable tracks - Auto-generated by Nomarr",
            "all": [{"gt": {"approachability": 0.7}}],
            "sort": "-approachability,-rating",
            "limit": 100,
        },
    }


def get_mixed_templates() -> dict[str, dict[str, Any]]:
    """Get mixed-criteria playlist templates."""
    return {
        "party_mix.nsp": {
            "name": "Party Mix",
            "comment": "High-energy dance party - Auto-generated by Nomarr",
            "all": [
                {
                    "any": [
                        {"contains": {"mood_strict": "happy"}},
                        {"contains": {"mood_strict": "energetic"}},
                        {"contains": {"mood_regular": "happy"}},
                    ]
                },
                {"contains": {"danceability": "danceable"}},
                {"gt": {"engagement": 0.6}},
            ],
            "sort": "-engagement,random",
            "limit": 75,
        },
        "chill_acoustic.nsp": {
            "name": "Chill Acoustic",
            "comment": "Relaxing acoustic tracks - Auto-generated by Nomarr",
            "all": [
                {
                    "any": [
                        {"contains": {"mood_strict": "relaxed"}},
                        {"contains": {"mood_strict": "calm"}},
                        {"contains": {"mood_regular": "calm"}},
                    ]
                },
                {"contains": {"nsynth_acoustic_electronic": "acoustic"}},
            ],
            "sort": "-rating,title",
            "limit": 100,
        },
        "upbeat_electronic.nsp": {
            "name": "Upbeat Electronic",
            "comment": "Happy electronic music - Auto-generated by Nomarr",
            "all": [
                {
                    "any": [
                        {"contains": {"mood_strict": "happy"}},
                        {"contains": {"mood_regular": "happy"}},
                    ]
                },
                {"contains": {"nsynth_acoustic_electronic": "electronic"}},
                {"gt": {"engagement": 0.5}},
            ],
            "sort": "-engagement,random",
            "limit": 100,
        },
        "mellow_electronic.nsp": {
            "name": "Mellow Electronic",
            "comment": "Calm electronic tracks - Auto-generated by Nomarr",
            "all": [
                {
                    "any": [
                        {"contains": {"mood_regular": "calm"}},
                        {"contains": {"mood_regular": "relaxed"}},
                    ]
                },
                {"contains": {"nsynth_acoustic_electronic": "electronic"}},
                {"lt": {"engagement": 0.5}},
            ],
            "sort": "approachability,-rating",
            "limit": 75,
        },
    }


def get_all_templates() -> dict[str, dict[str, Any]]:
    """
    Get all predefined playlist templates.

    Returns:
        Dictionary mapping filename to .nsp content dict
    """
    templates = {}
    templates.update(get_mood_templates())
    templates.update(get_style_templates())
    templates.update(get_quality_templates())
    templates.update(get_mixed_templates())
    return templates


def generate_template_files() -> dict[str, str]:
    """
    Generate all template files as JSON strings.

    Returns:
        Dictionary mapping filename to .nsp JSON content
    """
    templates = get_all_templates()
    return {filename: json.dumps(content, indent=2) for filename, content in templates.items()}


def get_template_summary() -> list[dict[str, str]]:
    """
    Get summary of all available templates.

    Returns:
        List of dicts with filename, name, comment
    """
    templates = get_all_templates()
    return [
        {
            "filename": filename,
            "name": content["name"],
            "comment": content["comment"],
        }
        for filename, content in templates.items()
    ]
