"""Deterministic synthetic report fixture generator (schema-v2, active catalog only).

Research-only.  Builds an **in-memory** DuckDB over the *current* schema
(``db._schema.ensure_schema``), seeds it entirely from synthetic data, runs the live
``report.run`` path, and writes the external fixture ``report.json`` under
``config.REPORT_DIR``.

The generated report is a **synthetic fixture** for the schema-v2
report/validator contract.  It is produced from deterministic in-memory data — it is
NOT the output of a real audio/model/corpus run, performs no inference at generation
time, and must never be cited as empirical retrieval evidence.  The emitted report
carries an explicit synthetic-fixture warning to that effect (validated by
``validate_fixture_report``).

The fixture exercises the schema-v2 contract:
  * EXACTLY the seven sections ``summary`` / ``corpus`` / ``analysis`` / ``winners`` /
    ``head-analysis`` / ``provenance`` / ``efficiency``;
  * active ``analyze_metrics`` rows with ``strategy_type = 'catalog'`` for deterministic
    EffNet AND MusicNN backbone populations (two catalog classes each, across K);
  * catalog strategy keys (``catalog:{backbone}:max_per_candidate_segment:v1:{keyset}``),
    finite metrics, active run ids + hashes, and sorted alias ids (equal representations
    counted once);
  * canonical head provenance (``boundary_source='catalog'`` /
    ``head_pool_variant='shared_catalog_boundary'``) for the EffNet backbone;
  * an active songs corpus; and
  * retained ``phase_timings`` restricted to the eight exact CLI phase names.

It never inserts any removed table and never emits forbidden legacy vocabulary.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Ensure the research tree is importable whether this runs under pytest (repo root on
# sys.path) or as ``python -m scripts.embedding_research.generate_fixture_report``.
_PKG_DIR = Path(__file__).resolve().parent
_ROOT = _PKG_DIR.parents[1]  # repo root (parent of scripts/)
for _p in (_ROOT, _PKG_DIR):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import duckdb

from scripts.embedding_research.config import REPORT_DIR
from scripts.embedding_research.db._schema import ensure_schema, upsert_phase_timing
from scripts.embedding_research.db.analyze_scope import write_catalog_analyze_rows
from scripts.embedding_research.db.head_phase import HeadPhaseProvenanceRow, write_head_phase_provenance
from scripts.embedding_research.db.provenance import write_run_provenance
from scripts.embedding_research.db.songs import upsert_song
from scripts.embedding_research.report import run as report_run

#: The eight exact CLI phase names (run.CLI_PHASES) allowed in fixture phase_timings.
PHASE_NAMES: tuple[str, ...] = (
    "ingest",
    "embed",
    "infer-heads",
    "catalog",
    "catalog-report",
    "analyze",
    "head-analysis",
    "report",
)

#: Deterministic backbone populations for the fixture (each seeded with its own classes).
FIXTURE_BACKBONES: tuple[str, ...] = ("effnet", "musicnn")

_SCORE_VARIANT = "max_per_candidate_segment"
_SEMANTICS_VERSION = 1

# Synthetic-warning emitted into the report (schema-v2 provenance/warnings surface).
SYNTHETIC_WARNING: dict = {
    "level": "info",
    "message": "SYNTHETIC FIXTURE — no empirical retrieval claim.",
    "detail": (
        "This report was generated by generate_fixture_report.py from deterministic "
        "in-memory (current-schema) synthetic catalog data for the EffNet and MusicNN "
        "backbone populations. It is a fixture for the schema-v2 report/validator "
        "contract — NOT the output of a real audio/model/corpus run — and must not be "
        "cited as empirical retrieval evidence."
    ),
}


def _catalog_key(backbone: str, keyset: str) -> str:
    return f"catalog:{backbone}:{_SCORE_VARIANT}:v{_SEMANTICS_VERSION}:{keyset}"


# ---------------------------------------------------------------------------
# Seeding
# ---------------------------------------------------------------------------


def _seed_songs(con) -> None:
    songs = [
        ("s1", "/audio/a/s1.flac", "Alice", "Songs of Alice", "One", "jazz"),
        ("s2", "/audio/a/s2.flac", "Alice", "Songs of Alice", "Two", "jazz"),
        ("s3", "/audio/b/s3.flac", "Bob", "Bob Tracks", "Three", "rock"),
        ("s4", "/audio/b/s4.flac", "Bob", "Bob Tracks", "Four", "rock"),
        ("s5", "/audio/c/s5.flac", "Carol", "Carol EP", "Five", "folk"),
    ]
    for song_id, path, artist, album, title, genre in songs:
        upsert_song(con, song_id, path, artist, album, title, genre)


def _seed_run_provenance(con, run_id: str) -> None:
    """Seed one active run's provenance history across all eight CLI phases.

    The ``analyze`` row is seeded with empty ``output_artifact_hashes`` so the catalog
    writer's run-scope bookkeeping appends its ``analyze_scope_v1`` lines to that single
    row (the real persistence path the report provenance scope-mapping consumes).
    """
    base = 1_700_000_000_000  # stable integer-ms anchor (deterministic)
    command = {
        "ingest": "python run.py ingest",
        "embed": "python run.py embed",
        "infer-heads": "python run.py infer-heads",
        "catalog": "python run.py catalog",
        "catalog-report": "python run.py catalog-report",
        "analyze": "python run.py analyze",
        "head-analysis": "python run.py head-analysis",
        "report": "python run.py report",
    }
    for idx, phase in enumerate(PHASE_NAMES):
        started = base + idx * 2_000
        write_run_provenance(
            con,
            run_id=run_id,
            phase=phase,
            status="completed",
            started_at=started,
            finished_at=started + 1_500,
            input_artifact_hashes="",  # analyze scope lines are appended by the writer
            output_artifact_hashes="",
            config_hash="abc123def4567890",
            song_count=5,
            warning_count=0,
            command_line=command[phase],
        )


def _seed_catalog_classes(con, run_id: str) -> None:
    """Seed active catalog analysis rows for EffNet and MusicNN populations.

    Each backbone gets TWO catalog classes over K in {5, 10}, so the winners section has a
    deterministic winner/delta/factor story per backbone.  EffNet class ``effnet:aa`` uses
    ``config_ids=(1, 5)`` to exercise sorted alias ids (equal representations counted once).
    """
    classes = [
        # EffNet population — two classes, one with an alias (1 canonical + 5 alias).
        {
            "backbone": "effnet",
            "keyset": "aa",
            "config_ids": (1, 5),
            "view": "viewhash-effnet-aa",
            "metrics": {"map_k": 0.55, "mrr": 0.45},
        },
        {
            "backbone": "effnet",
            "keyset": "bb",
            "config_ids": (3,),
            "view": "viewhash-effnet-bb",
            "metrics": {"map_k": 0.82, "mrr": 0.71},
        },
        # MusicNN population — independent two-class story.
        {
            "backbone": "musicnn",
            "keyset": "mm",
            "config_ids": (1,),
            "view": "viewhash-musicnn-mm",
            "metrics": {"map_k": 0.66, "mrr": 0.58},
        },
        {
            "backbone": "musicnn",
            "keyset": "m2",
            "config_ids": (2,),
            "view": "viewhash-musicnn-m2",
            "metrics": {"map_k": 0.61, "mrr": 0.52},
        },
    ]
    for k in (5, 10):
        for cls in classes:
            _persist_catalog_class(
                con,
                run_id=run_id,
                backbone=cls["backbone"],
                keyset=cls["keyset"],
                k=k,
                config_ids=cls["config_ids"],
                view_content_hash=cls["view"],
                metrics=cls["metrics"],
            )


def _persist_catalog_class(
    con,
    *,
    run_id: str,
    backbone: str,
    keyset: str,
    k: int,
    config_ids: tuple[int, ...],
    view_content_hash: str,
    metrics: dict[str, float],
) -> None:
    from scripts.embedding_research.common.catalog_analysis import CatalogAnalysisResult

    strategy_key = _catalog_key(backbone, keyset)
    result = CatalogAnalysisResult(
        run_id=run_id,
        backbone=backbone,
        config_ids=config_ids,
        representation_classes=(),
        k=k,
        view_content_hash=view_content_hash,
        score_variant=_SCORE_VARIANT,
        scoring_semantics_version=_SEMANTICS_VERSION,
        strategy_key=strategy_key,
        finite=True,
        metrics=dict(metrics),
        per_song={},
        per_query=(),
        n_queries=0,
        n_candidate_rows=0,
    )
    write_catalog_analyze_rows(con, run_id=run_id, result=result)


def _seed_head_provenance(con, run_id: str) -> None:
    """Canonical EffNet head-phase provenance (the head-analysis surface is EffNet-only)."""
    rows = [
        HeadPhaseProvenanceRow(
            run_id=run_id,
            config_id=1,
            backbone="effnet",
            head=head,
            bin_mode="temporal_global",
            threshold_configured=0.7,
            threshold_effective=0.7,
            semantics="direct_l2",
            status="done",
            n_songs=5,
            n_pooled=5,
            finite=True,
            reference_corpus_hash="ref-corpus-effnet",
        )
        for head in ("genre", "mood_happy")
    ]
    write_head_phase_provenance(con, rows)


def _seed_phase_timings(con, run_id: str) -> None:
    # Retained phase_timings hold ONLY the eight exact CLI phase names. Two run_ts values
    # (the active run + one historical run) so the report's efficiency section renders its
    # timing-history pivot alongside the per-phase bar chart.
    elapsed = {
        "ingest": 1.2,
        "embed": 3.4,
        "infer-heads": 2.1,
        "catalog": 4.5,
        "catalog-report": 0.8,
        "analyze": 5.0,
        "head-analysis": 1.1,
        "report": 0.2,
    }
    for run_ts in ("fixture-v2-previous", run_id):
        for phase in PHASE_NAMES:
            upsert_phase_timing(con, run_ts, phase, elapsed[phase])


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------


def build_fixture_con() -> duckdb.DuckDBPyConnection:
    """Build and seed an in-memory, current-schema DuckDB connection (no file writes)."""
    con = duckdb.connect(":memory:")
    ensure_schema(con)
    run_id = "fixture-v2-run"
    _seed_songs(con)
    _seed_run_provenance(con, run_id)
    _seed_catalog_classes(con, run_id)
    _seed_head_provenance(con, run_id)
    _seed_phase_timings(con, run_id)
    return con


def _inject_synthetic_warning(report_path: Path) -> None:
    """Append the synthetic-fixture warning to the emitted ``report.json``.

    ``report.run`` owns single-source assembly; the generator adds the fixture-only
    warning afterward so the generic report generator stays DB->report pure.
    """
    data = json.loads(report_path.read_text(encoding="utf-8"))
    warnings = data.setdefault("warnings", [])
    if not any(w.get("message") == SYNTHETIC_WARNING["message"] for w in warnings):
        warnings.append(SYNTHETIC_WARNING)
    report_path.write_text(json.dumps(data, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def main(report_dir: Path = REPORT_DIR) -> Path:
    """Regenerate the external schema-v2 fixture ``report.json`` under *report_dir*."""
    con = build_fixture_con()
    try:
        report_run(con, report_dir)
    finally:
        con.close()
    report_path = report_dir / "report.json"
    _inject_synthetic_warning(report_path)
    print(f"Fixture report written: {report_path}")
    return report_path


if __name__ == "__main__":  # pragma: no cover - CLI entry
    main()
